### ISSUE TITLE
Support for v2 in python

### ISSUE THREAD

**Issue by rvegas** [googleads/googleads-adsense-examples#16]
Hello and sorry for submitting an issue about this so directly, but I'm having a lot of issues migrating from `v1.4` to `v2` in python.

I've followed all of the release note changes and keep getting errors about parameters that are supposedly not supported.

I've tried updating google modules and libraries, but to no avail.

So, is there any effort being done to create the examples for `v2` before October 2021 since then the API will be deprecated and reports will be empty.

**Comment by donovanfm** [comment]
Hey, I'm happy to help assist you with the migration. We have already added [Python examples for v2](https://github.com/googleads/googleads-adsense-examples/tree/master/v2/python). If you're running into a specific error or if you would like to see an additional example, please let me know so I can help with that.

**Comment by rvegas** [comment]
@donovanfm thanks a lot! I will review the examples and they're normally quite helpful and explanatory.
