### ISSUE TITLE
Python Samples are not Updated for Python 3. Some dependencies are deprecated.

### ISSUE THREAD

**Issue by KevinTydlacka** [googleads/googleads-adsense-examples#9]
The samples here are written for python 2 which is deprecated. The samples also depend on the `oauth2client` library which Google also deprecated.

**Comment by BenRKarl** [comment]
For context @KevinTydlacka posted a related issue on the [`google-auth`](https://github.com/googleapis/google-auth-library-python) library Issues tracker:

https://github.com/googleapis/google-auth-library-python/issues/456

**Comment by donovanfm** [comment]
Hi, Kevin. Thanks for alerting us about this. We're working on rewriting all of our AdSense Management API client library examples, so we'll address these concerns in this rewrite.

**Comment by donovanfm** [comment]
The Python examples have been updated to use Python 3, to remove the oauth2client dependency, and to make calls against v2 of the AdSense Management API.

https://github.com/googleads/googleads-adsense-examples/tree/master/v2/python
